name: Weekly Stats Report

on:
  workflow_run:
    workflows:
      - 'Merge Open PRs'
    types:
      - completed

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Check today is Sunday
        id: check-sunday
        run: |
          DAY_OF_WEEK=$(date +'%u')
          if [ "$DAY_OF_WEEK" -ne 7 ]; then
            echo "Not Sunday. Exiting."
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract closed pull requests using API
        id: list-prs
        run: |
          PRS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed")

          echo "$PRS" > pr_data.json

      - name: Fetch Labels from Repository
        id: fetch-labels
        run: |
          LABELS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/labels")

          echo "$LABELS" > label_data.json

      - name: Upload PR and Label Data
        uses: actions/upload-artifact@v4
        with:
          name: pr-and-label-data
          path: |
            pr_data.json
            label_data.json

      - name: Analyze PRs and Generate Stats
        id: generate-stats
        run: |
          python .github/workflows/generate_weekly_stats.py pr_data.json target_goals.json label_data.json weekly_stats.md

      - name: Post Weekly Stats
        run: |
          CONTENT=$(cat weekly_stats.md)
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title": "n주차 정산", "body": "'"$CONTENT"'"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues"
      
      - name: Upload weekly stats
        uses: actions/upload-artifact@v4
        with:
          name: weekly-stats
          path: weekly_stats.md
